version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ml-bot-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-stma7atjrja2"
s3_prefix = "ml-bot-dev"
region = "cn-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

